apiVersion: apps/v1
kind: Deployment
metadata:
  name: beginner-html-site-styled
spec:
  replicas: 5
  selector:
    matchLabels:
      app: beginner-html-site-styled
  template:
    metadata:
      labels:
        app: beginner-html-site-styled
    spec:
      containers:
      - name: website
        image: jithajothinadh/beginner-html-site-styled
        ports:
        - containerPort: 80
